### ISSUE TITLE
[Bug]: 随便逛逛,自定义的permalink进不了。（小白）

### ISSUE THREAD

**Issue by backunderstar** [anzhiyu-c/hexo-theme-anzhiyu#1]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.02

### 使用的浏览器？ || What browse are you using?

Edge

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

![image](https://img01.anzhiy.cn/useruploads/90/2023/04/02/642907efbfb59.png)
鱼~，随便逛逛会出现这个问题，好像自动生成的permalink会，自定义的permalink就会进不去，不知道是什么原因。
很舒服的主题，多有打扰，非常感谢！

### 出现问题的网站 | Website

new.backunderstar.com

**Comment by anzhiyu-c** [comment]
随便逛逛只能进入文章界面，不支持其他界面，因为随机的js只随机了文章，并使用pjax跳转。

**Comment by backunderstar** [comment]
好的，谢谢鱼～，我还想问下，用addrlink生成的永久链接文章，随便逛逛是可以逛到的吧。

**Comment by anzhiyu-c** [comment]
可以的，只要是文章就可以，后面我会出视频教程。
