### ISSUE TITLE
[Bug]: card_archives 鬼畜

### ISSUE THREAD

**Issue by HimiCos** [anzhiyu-c/hexo-theme-anzhiyu#11]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.1.2

### 使用的浏览器？ || What browse are you using?

Arc

### 使用的系统？ || What operating system are you using?

macOS

### 问题描述 | Describe the bug

当鼠标移到控件上会鬼畜
和页面大小有关

https://user-images.githubusercontent.com/92566148/231154279-e3ddcfce-b1ea-428d-b630-c01d7db78c51.MOV

### 出现问题的网站 | Website

https://blog.himicos.cc

**Comment by anzhiyu-c** [comment]
下个版本修复。

**Comment by HimiCos** [comment]
收到👌
