### ISSUE TITLE
[Feature]: 支持bilibili视频卡片和豆瓣页面卡片功能

### ISSUE THREAD

**Issue by lz732895965** [anzhiyu-c/hexo-theme-anzhiyu#111]
### 想要的功能 | What feature do you want?

如题，目前已有博主开发出bilibili视频卡片效果，相关链接如下。希望渔大佬开发相关功能。
https://blog.leonus.cn/2023/butterflyTag-1.html

**Comment by anzhiyu-c** [comment]
下个版本将被支持
配置文件中

参考 https://blog.leonus.cn/2023/butterflyTag-1.html 进行自建
```yml
bilibiliApi: https://api.320.ink/api/b
```
文章使用
{% bilibili https://www.bilibili.com/video/BV1eh411G7bK 00:29 %}

**Comment by ayakasuki** [comment]
> 下个版本将被支持 配置文件中
> 
> 参考 https://blog.leonus.cn/2023/butterflyTag-1.html 进行自建
> 
> ```yaml
> bilibiliApi: https://api.320.ink/api/b
> ```
> 
> 文章使用 {% bilibili https://www.bilibili.com/video/BV1eh411G7bK 00:29 %}

配置文件中 bilibiliApi: https://api.320.ink/api/b 是哪个配置文件呢_config_anzhiyu?但是里面好像没有替换的选项
