### ISSUE TITLE
[Bug]: 人潮汹涌有时候会变白，再刷新一下就好了

### ISSUE THREAD

**Issue by cuixinyu0427** [anzhiyu-c/hexo-theme-anzhiyu#117]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.6

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

不是必现，不知道什么原因导致的
https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/70997227/a6b4ef98-9929-44e1-8cf8-d5cce80ad98c

### 出现问题的网站 | Website

本地跑的

**Comment by Joker2Yue** [comment]
可能是代理/CDN等问题

**Comment by ayakasuki** [comment]
确实每次都要重新刷新一下
