### ISSUE TITLE
[Bug]: 文章背景色无法修改

### ISSUE THREAD

**Issue by hulebaji** [anzhiyu-c/hexo-theme-anzhiyu#119]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.6

### 使用的浏览器？ || What browse are you using?

Edge

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

参照文档修改Post Front-matter

background | 【可选】文章背景可配置为 16 进制颜色值

尝试了

background: "#8ed6c6"
background: #8ed6c6
等结果均无效，并没有成功修改文章背景颜色

### 出现问题的网站 | Website

*

**Comment by anzhiyu-c** [comment]
该参数已被移除，将在文档中进行更新。
