### ISSUE TITLE
[Bug]: ptool 中的 share_copyurl 失效

### ISSUE THREAD

**Issue by 1an8r0wn** [anzhiyu-c/hexo-theme-anzhiyu#122]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.6

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

macOS

### 问题描述 | Describe the bug

![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/48291064/ab882392-4508-438b-bb16-24495eb9e675)
![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/48291064/e9a63fa4-2531-49a0-87bd-d0ac7ff07027)

F12 检查提示如下：

(index):204 Uncaught ReferenceError: rm is not defined
    at HTMLDivElement.onclick ((index):204:3475)
onclick @ (index):204

### 出现问题的网站 | Website

https://hexo-zeta-silk.vercel.app/

**Comment by anzhiyu-c** [comment]
大概是因为没有开启右键菜单导致的，将在下一个版本1.6.9+修复。

**Comment by 1an8r0wn** [comment]
> 大概是因为没有开启右键菜单导致的，将在下一个版本1.6.9+修复。

已测试验证，的确是没有开启右键导致的。

**Comment by anzhiyu-c** [comment]
该问题已被修复。
