### ISSUE TITLE
[Bug]: 切换显示模式之后主题色不能马上改变

### ISSUE THREAD

**Issue by RicharPao** [anzhiyu-c/hexo-theme-anzhiyu#125]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.8

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

在深色模式下，主题色应为黄色，但是现在是深浅模式的主题色混搭，似乎是因为深色模式下的颜色变量没有 anzhiyu-main，anzhiyu-theme等变量
不知道是鱼佬刻意这样设计的（如果是可以直接close了）还是BUG？
![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/99643174/1433fe04-4e00-4ac1-b1b9-19af9dc2f3e9)

### 出现问题的网站 | Website

https://vacuole.top

**Comment by RicharPao** [comment]
emm。。。部署之后就好了，也许是缓存的问题

**Comment by RicharPao** [comment]
但是这还是个问题啊，切换显示模式之后主题色不能马上更换，总不能每次都清缓存再刷新吧
![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/99643174/bfc38191-69e2-410f-b13d-7ebc90aa0c7e)
![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/99643174/76d8d7a4-0ddf-4300-ba52-f67163393f3f)

**Comment by Joker2Yue** [comment]
检查主色调配置：

# 主色调相关配置
mainTone:
  enable: true # true or false 文章是否启用获取图片主色调
  mode: both # cdn/api/both cdn模式为图片url+imageAve参数获取主色调，api模式为请求API获取主色调，both模式会先请求cdn参数，无法获取的情况下将请求API获取

**Comment by anzhiyu-c** [comment]
经过排查，可能导致的问题为右键菜单，将在下个版本修复。

**Comment by anzhiyu-c** [comment]
该问题已被修复。
