### ISSUE TITLE
[Bug]: 顶部跳转会有重叠现象

### ISSUE THREAD

**Issue by cuixinyu0427** [anzhiyu-c/hexo-theme-anzhiyu#133]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.6

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/70997227/e971ebff-662c-4366-b0ec-3de704df81fe

顶部跳转会有重叠现象

### 出现问题的网站 | Website

https://blog.cuixinyu.com/

**Comment by anzhiyu-c** [comment]
暂不提供魔改后的帮助，可以排查一下是否阻塞了main.js，导致main.js中的变量阻塞。
