### ISSUE TITLE
[Bug]: 是否支持二级目录

### ISSUE THREAD

**Issue by xxmy7** [anzhiyu-c/hexo-theme-anzhiyu#146]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.8

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

希望配置网页如下：
```
url: https://username.github.io/blog
root: /blog/
```
但是打开分类页面后，点击分类页面下的分类类别，跳转不到正确的url，正确的应该是`https://username.github.io/blog/categories/xxx/`,但是实际情况下丢失了二级目录，即`https://username.github.io/categories/xxx/`,导致出现404

### 出现问题的网站 | Website

0

**Comment by anzhiyu-c** [comment]
将在下个版本得到改善。

**Comment by anzhiyu-c** [comment]
该问题已被修复。

**Comment by DamonHu** [comment]
今天使用最新的release版本1.6.13和dev分支的版本测试，该问题依旧存在。如果是二级目录，点击分类页面下的分类类别和首页的分类类别，都会出现404报错 @anzhiyu-c

**Comment by DamonHu** [comment]
另外在点击右上角的随机文章按钮，控制台报错toRandomPost is not defined，不会随机切换文章。希望大佬也顺带看看
