### ISSUE TITLE
[Bug]: about界面的技能列表为空

### ISSUE THREAD

**Issue by xiaoqi419** [anzhiyu-c/hexo-theme-anzhiyu#147]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.9

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

如图
![屏幕截图 2023-11-08 001115](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/84332917/1758f131-288b-44ff-a7d3-fed04bdab857)

### 出现问题的网站 | Website

www.ojason.top/about

**Comment by CoderLuShi** [comment]
https://docs.anheyu.com/advanced/#%E9%A6%96%E9%A1%B5%E6%8A%80%E8%83%BD%E7%82%B9%E9%85%8D%E7%BD%AE
这里，把技能点配置上就像可以了
