### ISSUE TITLE
[Bug]: 点击关于我的页面中的  “为TA充电” 报错。

### ISSUE THREAD

**Issue by baojunz** [anzhiyu-c/hexo-theme-anzhiyu#149]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.9

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

macOS

### 问题描述 | Describe the bug

点击关于我的页面中的  “为TA充电” 报错。

![be9740593f63638fb3c975953773f100](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/48702961/769d3576-1e59-43cd-9e1b-b72f2c2951a7)

![e9e58faf00b205cf04f9cbd49213db91](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/48702961/9710f3be-e23b-4dc9-ba6d-94eb08c62895)

### 出现问题的网站 | Website

blog.buuu.cn

**Comment by anzhiyu-c** [comment]
暂时可以通过开启控制台解决，该问题将在下个版本得到改善。
