### ISSUE TITLE
[Bug]: 1.6.9版本文章顶部图倾斜放大问题

### ISSUE THREAD

**Issue by yeyulemon** [anzhiyu-c/hexo-theme-anzhiyu#150]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.9

### 使用的浏览器？ || What browse are you using?

Edge

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/125271764/d7f34737-0e94-4974-afc4-f9816f68bf49)

1.6.9版本背景图片没有发生倾斜。

### 出现问题的网站 | Website

https://blog.yeyulemon.top/posts/6782be63/

**Comment by yeyulemon** [comment]
啊呜，鱼佬救命

**Comment by yeyulemon** [comment]
我这图为啥不是歪的靠右且放大

**Comment by anzhiyu-c** [comment]
开启mainTone.enable
