### ISSUE TITLE
[Bug]: 文章详情页，当文章目录特别多时，鼠标在目录区域，目录区域不能滚动，很想滚到后面目录之后点击目录快速跳到对应文章区块

### ISSUE THREAD

**Issue by yzxcxya** [anzhiyu-c/hexo-theme-anzhiyu#152]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

最新版本 1.6.9

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/41381007/2d232262-b0da-410c-8012-317e6188ff3f)
文章详情页，当文章目录特别多时，鼠标在目录区域，目录区域不能滚动，很想滚到后面目录之后点击目录快速跳到对应文章区块，希望目录这里能有个滚动条可以滚动

### 出现问题的网站 | Website

http://localhost:4000/

**Comment by anzhiyu-c** [comment]
1.6.10版本已解决该问题。
