### ISSUE TITLE
[Bug]: 由于 npm js 上游更新导致 GET 404

### ISSUE THREAD

**Issue by SmallKi-d** [anzhiyu-c/hexo-theme-anzhiyu#156]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.10

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

macOS

### 问题描述 | Describe the bug

在默认 CDN 情况下，出现了找不到 CDN 的情况，如图:

<img width="918" alt="image" src="https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/25631432/387298c7-8a9b-4596-8aa1-1e7e9b4e6757">

目前自行的解决方案是全部采用 custom CDN 并将版本号更改为 latest

### 出现问题的网站 | Website

blog.kclub.tech (已自行更换 CDN )

**Comment by SmallKi-d** [comment]
同时elemecdn的npm包版本过于滞后，如果直接获取latest的js的话，以instantsearch.js为例，elemecdn差了20余个版本

**Comment by anzhiyu-c** [comment]
可以通过配置CDN选项来修改。

**Comment by anzhiyu-c** [comment]
Hello @SmallKi-d,  please input issue by template and add detail. Issues labeled by Need More Info will be closed if no activities in 7 days.
你好 @SmallKi-d，请按照issue模板填写, 并详细说明问题和复现步骤等, 60天内未回复issue自动关闭。

**Comment by SmallKi-d** [comment]
那样默认CDN无效的话，就没有存在的意义了

**Comment by anzhiyu-c** [comment]
默认cdn版本在很久之前就已经不是elemecdn了
