### ISSUE TITLE
[Bug]: Macos Safari浏览器下，右上角”更多推荐“字溢出

### ISSUE THREAD

**Issue by vveg26** [anzhiyu-c/hexo-theme-anzhiyu#163]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.10

### 使用的浏览器？ || What browse are you using?

Safari

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

macOS

### 问题描述 | Describe the bug

<img width="606" alt="image" src="https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/62206240/1d166a16-4663-4917-8524-8a5f42428465">

### 出现问题的网站 | Website

https://yuhang.online

**Comment by vveg26** [comment]
1.6.8及之前版本没有问题，从1.6.9之后开始出现

**Comment by jcdiv47** [comment]
贡献一个dp：我这边Sonoma 14.2 Safari 能够复现该bug，同一台MBP的Chrome则正常。
