### ISSUE TITLE
[Feature]: 增加标题前图标

### ISSUE THREAD

**Issue by HysenEcho** [anzhiyu-c/hexo-theme-anzhiyu#164]
### 想要的功能 | What feature do you want?

标题前图标设置了，但是不生效，我看鱼本人的网页标题前也没有图标

**Comment by sun0225SUN** [comment]
哪里的图标，可以截张图嘛 👀

**Comment by anzhiyu-c** [comment]
没有标题前图标功能，只能修改标题后的link图标。
