### ISSUE TITLE
[Feature]: 左下角音乐球的默认配置

### ISSUE THREAD

**Issue by OcrSu** [anzhiyu-c/hexo-theme-anzhiyu#166]
### 想要的功能 | What feature do you want?

新增一个 左下角音乐球的配置。
配置的功能为：自动播放和音量大小。

我没有技术，但我尝试过在各种config中添加 aplayer metingjs的autoplay，volume参数，不过没有一个有用的。
希望能添加一个更方便的配置位置。

**Comment by anzhiyu-c** [comment]
优先支持，下个版本支持。
