### ISSUE TITLE
[Bug]: 图标

### ISSUE THREAD

**Issue by TY10909** [anzhiyu-c/hexo-theme-anzhiyu#17]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.4

### 使用的浏览器？ || What browse are you using?

Chrome

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

更新之后本地可以显示图标，部署到vercel之后就不显示了。也更换了浏览器，在手机端也测试了，均无法显示，并未更改源码
![1](https://user-images.githubusercontent.com/112875745/231776985-f0de532a-1b5d-4dac-923e-a9bf61e5e236.png)
![2](https://user-images.githubusercontent.com/112875745/231777013-f786df46-70d7-4be1-8ec6-d3b7ad24dd9c.png)
![3](https://user-images.githubusercontent.com/112875745/231777023-4a7e6b1d-2f05-4e30-be1a-4b1e017f2f8f.png)

### 出现问题的网站 | Website

blog.200319.xyz

**Comment by TY10909** [comment]
不太懂您的意思，我是直接将本地1.2版本删除，1.4拉下到本地，将主题文件比对后更新的。

**Comment by anzhiyu-c** [comment]
配置文件未完全正确。
