### ISSUE TITLE
[Bug]: 下一篇悬浮气泡遮挡内容，且无法关闭

### ISSUE THREAD

**Issue by jitcor** [anzhiyu-c/hexo-theme-anzhiyu#173]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.12

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/27600008/6c4d8dc2-6acb-4a74-a4a1-78aa24ac2ee2)
如图所示，后面的内容被遮挡了，而且这个悬浮窗还关不掉

### 出现问题的网站 | Website

https://blog.anheyu.com/posts/b228.html

**Comment by jitcor** [comment]
建议可以加个关闭按钮，或者把显示位置变一下

**Comment by anzhiyu-c** [comment]
此时已经翻到文章底部（阅读已完成），因该引导用于进行阅读下一篇文章，所以改问题不会被修复，可以自行修改一下css调整
