### ISSUE TITLE
[Bug]: 音乐馆页面的歌单无法在主配置文件更换

### ISSUE THREAD

**Issue by MGHYGitHub** [anzhiyu-c/hexo-theme-anzhiyu#174]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.12

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

(已寻求他人远程协助修复了)
在_config.anzhiyu.yml配置这个,然后根据文档的提示去整音乐馆页面,发现歌单无法自动更换.
在utils.js进行手动更换才可以替换歌单
没在文档中看到关于这里的一些细节的教程--(纯萌新
![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/113328471/0d38f3e5-601c-4e85-a5ae-3979d898a534)

![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/113328471/29b0dfc8-f370-499e-a135-4e46ffdbf7c9)

### 出现问题的网站 | Website

https://mghy.top/

**Comment by Xyyaua** [comment]
这个[官方文档](https://docs.anheyu.com/page/music.html)已经说了
拉到下面就有了

原内容：
将`menu`中音乐馆的路径修改为以下格式即可`/music/?id=1708664797&server=tencent`，支持`id`和`server`参数。

**Comment by MGHYGitHub** [comment]
> 这个[官方文档](https://docs.anheyu.com/page/music.html)已经说了 拉到下面就有了
> 
> 原内容： 将`menu`中音乐馆的路径修改为以下格式即可`/music/?id=1708664797&server=tencent`，支持`id`和`server`参数。

可以具体点吗?我对这些不怎么了解,完全萌新.
所说的menu是开头的导航栏哪里吗?
应该是这样吗?可是如果我想要直接/music/的话不想后面显示`?id=1708664797&server=tencent`这条的话,我只能在utils.js文件中直接修改id和server

原来nav_music:是左下角音乐球的配置好吧:D
![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/113328471/2ba351b4-1327-49bd-959e-8bb6f353d60f)

**Comment by Xyyaua** [comment]
是在menu改的
比如
```yml
menu:
  我的:
    音乐馆: /music/ || icon-music
```
就可以改成
```yml
menu:
  我的:
    音乐馆: /music/?id=1708664797&server=tencent || icon-music
```
这样就可以自定义歌单了  
不过不想在后面显示`id`和`server`的确实只能改js了
