### ISSUE TITLE
[Bug]: “首页” 不对齐

### ISSUE THREAD

**Issue by son-g0ku** [anzhiyu-c/hexo-theme-anzhiyu#178]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.12

### 使用的浏览器？ || What browse are you using?

Other

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

macOS

### 问题描述 | Describe the bug

首页 与 更多 不对齐
浏览器是 FF，在 Chrome 是对齐的。
<img width="1472" alt="image" src="https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/152959149/a42d42e3-8ce7-4a4f-8e8a-3749e8b50034">

**Comment by WangLanHuaJiaoFen** [comment]
使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?
1.6.12

使用的浏览器？ || What browse are you using?
edge

是否修改过主题文件？ || Has the theme files been modified?
不是 (No)

使用的系统？ || What operating system are you using?
windows

问题描述 | Describe the bug
正常流程下载过主题后，hexo s报ERROR
![WRTFI@S$X KSVHJG~88%Q{M](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/126872692/1eb3e8d1-e6e6-4cda-bb47-935cfe249789)

**Comment by anzhiyu-c** [comment]
该问题暂时无法复现。仅适配Chrome等主流浏览器，欢迎pr
