### ISSUE TITLE
[Bug]: “安知鱼和风”天气插件无法关闭

### ISSUE THREAD

**Issue by SmallKi-d** [anzhiyu-c/hexo-theme-anzhiyu#183]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.12

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

macOS

### 问题描述 | Describe the bug

<img width="408" alt="Screenshot 2024-01-02 at 15 22 17" src="https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/25631432/0486ae4a-ccc7-46f0-9ff8-61f17a5598e1">
<img width="1167" alt="image" src="https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/25631432/28953479-8b51-478a-8ba8-5bd1751f959f">
<img width="1167" alt="image" src="https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/25631432/85fabe5a-9a35-4d5a-a2be-1665f9818686">

### 出现问题的网站 | Website

blog.kclub.tech

**Comment by anzhiyu-c** [comment]
```yml
# nav相关配置
nav:
  enable: true
  travelling: true
  clock: false # 和风天气开关
```

将clock改为false
