### ISSUE TITLE
[Bug]: mac上safari图标失效

### ISSUE THREAD

**Issue by cuixinyu0427** [anzhiyu-c/hexo-theme-anzhiyu#186]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.9

### 使用的浏览器？ || What browse are you using?

Safari

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

macOS

### 问题描述 | Describe the bug

网站图标变成蓝色小方块
![微信图片_20240115110636](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/70997227/429681d7-0c5c-4111-aeff-b30637b49a7e)

### 出现问题的网站 | Website

https://blog.cuixinyu.com/

**Comment by cuixinyu0427** [comment]
Chrome没问题，我自己的和鱼的在safari上都是蓝色小方块，洪哥的能显示

**Comment by SmallKi-d** [comment]
同样有这个问题，请问解决了么？

**Comment by anzhiyu-c** [comment]
<img width="1661" alt="image" src="https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/73864136/00b86458-ff0f-4215-aa20-a9884f72592d">
