### ISSUE TITLE
[Bug]: 即刻说说配置video使用bilibili链接点不进去视频显示图片未找到，盲猜目前只支持mp4

### ISSUE THREAD

**Issue by cuixinyu0427** [anzhiyu-c/hexo-theme-anzhiyu#189]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.12

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

![0d5773a7a1ea4c2a0b6322a497a9527](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/70997227/4d736c00-3ea0-41a9-bb96-dcf2204341e6)
![d73ef3aec8f39c813c8d120867d840b](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/70997227/83e0c68d-7cd9-41ee-8d25-522189d9f63b)
![e3a253c90e77befcd5c89d04a19116e](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/70997227/8dfecbdf-b2df-4573-b525-0a532e432e60)

### 出现问题的网站 | Website

本地跑的

**Comment by hulebaji** [comment]
你好啊👋，这是可以实现的哦，我之前也有遇到类似的问题，但是仔细翻阅文档之后发现是地址填写错误了，在主题文档中有写到**视频为player.bilibili.com的将显示为bilibili视频**
https://docs.anheyu.com/page/essay.html
![1706332991587](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/62818915/61a13e7e-df6e-41bc-842e-fdd2c1d00b7f)
有关于player.bilibili的内容可以参阅以下文档
https://player.bilibili.com/
相信你可以根据文档玩出更多花样来

另外您截图中的这部番剧在即刻短文中链接的正确写法如下：
https://player.bilibili.com/player.html?aid=4696940&autoplay=0
后面的数字4696940为该视频的av号
![微信截图_20240127133424](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/62818915/9e581ac2-e4a7-4168-8970-285e6d3889f2)

希望这段内容有帮助到你！
