### ISSUE TITLE
[Feature]: 建议加个默认配置文件，减少配置文件的复杂性

### ISSUE THREAD

**Issue by juzzia** [anzhiyu-c/hexo-theme-anzhiyu#191]
### 想要的功能 | What feature do you want?

首先谢谢作者开源这个精美的主题项目，我在使用过程发现点问题，提一点小建议
我认为配置文件太复杂了，长达1250行的配置文件着实让人眼花缭乱，有些配置项比如聊天，评论什么需要额外部署这些配置可能使用率不高，但是这种配置多了就会导致配置文件配置项很多，所以我建议新建一个默认配置文件 default_config.yml ，config.yml只保留目前enable为true的配置，先读取默认配置 default_config.yml，然后再读取config.yml配置做一个覆盖，这样config.yml配置就会简单很多，对目前工程项目也不会因为缺失配置项而导致报错

**Comment by anzhiyu-c** [comment]
请注意_config.anzhiyu.yml中的配置优先级大于_config.yml，所以更新主题后需要比对主题文件夹中的theme/anzhiyu/_config.yml 文件内容，一般在[release](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/releases) 的说明里会特别提示或给出配置文件版本对比diff，同步修改原配置文件即可。
