### ISSUE TITLE
[Bug]: 带有链接的图片自动换行

### ISSUE THREAD

**Issue by hexadecimal233** [anzhiyu-c/hexo-theme-anzhiyu#199]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.12

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

在我把图片的链接放进来并加上跳转的时候发现渲染出来的网页里带有链接的图片自动换行了
左侧出现链接标识，中间断开
![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/62250232/f4e96c99-5f02-4947-933f-da6c867a06f8)

### 出现问题的网站 | Website

https://me.onlyra1n.top/about/

**Comment by sun0225SUN** [comment]
你为啥要这样做，按照这个格式书写即可。
<img width="1490" alt="image" src="https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/79169717/528750cc-a944-401b-b882-066162d657eb">

**Comment by LLKawi** [comment]
> 你为啥要这样做，按照这个格式书写即可。 <img alt="image" width="1490" src="https://private-user-images.githubusercontent.com/79169717/303190208-528750cc-a944-401b-b882-066162d657eb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTY0NjQsIm5iZiI6MTcwNzM5NjE2NCwicGF0aCI6Ii83OTE2OTcxNy8zMDMxOTAyMDgtNTI4NzUwY2MtYTk0NC00MDFiLWI4ODItMDY2MTYyZDY1N2ViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDEyNDI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1NzA5N2ExNzFlYjgwNzhlMDJmOWQ0ZjUzZDdiZDgwZWU5Njg2YmRhNmNkOWUxNDk3ZDhlYzg4OWJlMzE4YjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uhWnxFactOWIG2C_w96_gqsH7rcHEwqoc5xT8G9Qvek">

bug总是要修的，不修放在那里依旧是bug。
放在footer的badge多了也乱

**Comment by sun0225SUN** [comment]
刚理解你意思，一开始以为你在DIY页脚徽章（因为这玩意通常出现在页脚）。
主题 CSS 把 img 的 display 属性固定成 block了，也不算Bug，你可以自定义CSS改成内联即可。

```css
#article-container img {
  display: inline-block;
}
```

**Comment by LLKawi** [comment]
![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/62250232/0990dfa9-d4e8-4b52-b692-8c2f91cf5090)
先放这吧
