### ISSUE TITLE
[Bug]: social图标及nav左边菜单

### ISSUE THREAD

**Issue by IMF5er** [anzhiyu-c/hexo-theme-anzhiyu#2]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.0.4

### 使用的浏览器？ || What browse are you using?

Chrome

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

鱼佬，social图标，改了主题的配置文件后，删除部分图标后，页面上还是会显示图标存在，nav左侧菜单也是这样的

### 出现问题的网站 | Website

本地搭建的

**Comment by dazhuang17** [comment]
social图标和nav左侧菜单还有底部footer显示的安知鱼上班了啥的，修改没反应，我是删除/themes/anzhiyu/_config.yml文件就行了

**Comment by dazhuang17** [comment]
你知道左上角的天气那个在哪儿改么.....

**Comment by anzhiyu-c** [comment]
> social图标和nav左侧菜单还有底部footer显示的安知鱼上班了啥的，修改没反应，我是删除/themes/anzhiyu/_config.yml文件就行了

下个版本修复。

**Comment by anzhiyu-c** [comment]
> 你知道左上角的天气那个在哪儿改么.....

天气默认获取当地位置，获取不到默认北京。

**Comment by dazhuang17** [comment]
> > 你知道左上角的天气那个在哪儿改么.....
> 
> 天气默认获取当地位置，获取不到默认北京。

我觉得可以在配置文件里加个开关......因为我没显示过除潍坊之外其他的地儿（如果不麻烦的话...）

**Comment by anzhiyu-c** [comment]
已修复，下个版本提供配置项。
