### ISSUE TITLE
[Bug]: hexo s报错

### ISSUE THREAD

**Issue by WangLanHuaJiaoFen** [anzhiyu-c/hexo-theme-anzhiyu#206]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.12

### 使用的浏览器？ || What browse are you using?

Edge

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

hexo s后报ERROR
![WRTFI@S$X KSVHJG~88%Q{M](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/126872692/c5da1962-5288-4fbb-847d-a9dde3b03b31)

### 出现问题的网站 | Website

none

**Comment by jesusLove** [comment]
重新 `npm install`，执行 `npx hexo s`  试试呢？

**Comment by anzhiyu-c** [comment]
Hello @WangLanHuaJiaoFen,  please input issue by template and add detail. Issues labeled by Need More Info will be closed if no activities in 7 days.
你好 @WangLanHuaJiaoFen，请按照issue模板填写, 并详细说明问题和复现步骤等, 60天内未回复issue自动关闭。
