### ISSUE TITLE
[Feature]:  支持 giscus 评论

### ISSUE THREAD

**Issue by mobeicanyue** [anzhiyu-c/hexo-theme-anzhiyu#213]
### 想要的功能 | What feature do you want?
![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/81098819/95845558-c9d4-4f9e-9b89-b394b940e8eb)

看文档主题好像只支持两种评论，希望可以加上这一款依赖于 Github discussion的评论
https://giscus.app/zh-CN

**Comment by TungLamC** [comment]
同求，照着 butterfly 的教程来配置 giscus 评论没有配置成功，希望 anzhiyu 也可以支持一下 giscus 评论系统
