### ISSUE TITLE
[Bug]: Twikoo 本地、托管容器自带域名、自定义域名的样式与演示效果不符。

### ISSUE THREAD

**Issue by JonasTech0** [anzhiyu-c/hexo-theme-anzhiyu#217]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.12

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

我在使用您的 Hexo 主题 [anzhiyu](https://github.com/anzhiyu-c/hexo-theme-anzhiyu) 时遇到了一些问题，我相信提供详细的情况描述，将有助于您更好地理解和解决这些问题。

**问题描述：**

我注意到在不同环境下，我的网站中Twikoo的外观呈现出了不同的样式。以下是详细的环境描述和遇到的情况：

### 3. **Zeabur托管环境：** 部署在Zeabur并使用Zeabur生成的后缀为zeabur.app域名时，网站恢复正常，显示预期的样式。![Zeabur托管样式](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/128354383/5cbd6697-d38d-4456-90b9-6ab0774b651d)

在所有这些环境中，我检查了控制台，未发现任何明显的错误提示。

**请求的帮助：**

我希望能得到您的指导，以解决在自定义域名绑定下样式不一致的问题。特别是，我想了解可能导致这种差异的原因，以及如何调整配置以确保在所有环境中都能获得一致的外观。

感谢您抽时间阅读我的反馈。对于您可能提供的任何帮助或建议，我将不胜感激。如果需要更多信息，请随时联系我。

祝好

### 出现问题的网站 | Website

https://www.jonastech.cc
https://jonastech.zeabur.app

**Comment by GnaixEuy** [comment]
建议排查一下是不是那个css文件没成功拉下来，我部署是正常的

**Comment by JonasTech0** [comment]
> 建议排查一下是不是那个css文件没成功拉下来，我配置是正常的

感谢您的回复。基于您的描述，我已经排除了缓存、前端代码问题、API问题、权限问题以及发布流程相关的可能性，因为我尝试了通过Git克隆项目，以及直接从GitHub下载源代码，遇到的问题依然相同。我现在的疑惑主要集中在一个特定的现象上：为什么通过容器部署后生成的域名可以正常显示内容，这一点令人困惑。这种情况表明，可能存在与部署环境或配置相关的特定问题。我需要再研究研究。

**Comment by GnaixEuy** [comment]
<img width="973" alt="截屏2024-04-02 21 07 02" src="https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/78402118/0a35f994-e440-460a-a72e-0935f1a6ed3c">
<img width="952" alt="截屏2024-04-02 21 07 18" src="https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/78402118/bf317d40-569c-4dcf-b1db-96cfd7d8ab79">
我对比了我们两个按钮差异的样式，css是有明显差异的，前缀为anzhiyu的丢失，可以检查一下是否存在自定义样式或者对主题的修改导致的问题，祝早日修复

**Comment by JonasTech0** [comment]
> <img alt="截屏2024-04-02 21 07 02" width="973" src="https://private-user-images.githubusercontent.com/78402118/318789591-0a35f994-e440-460a-a72e-0935f1a6ed3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNzMzMzUsIm5iZiI6MTcxMjA3MzAzNSwicGF0aCI6Ii83ODQwMjExOC8zMTg3ODk1OTEtMGEzNWY5OTQtZTQ0MC00NjBhLWE3MmUtMDkzNWYxYTZlZDNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE1NTAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5MTM4MmUyYWM0YjQ2OTdlYTY2NDI3ZjlhZGYwMWYwOTFkNGNlNmQ3Njk4MzUwZjY5OGIzMTNiMzAxODkwMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LnK1kNIp_jQifx_NXWb4M7I13Bx5siDjI887NZF9QwQ"> <img alt="截屏2024-04-02 21 07 18" width="952" src="https://private-user-images.githubusercontent.com/78402118/318789669-bf317d40-569c-4dcf-b1db-96cfd7d8ab79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNzMzMzUsIm5iZiI6MTcxMjA3MzAzNSwicGF0aCI6Ii83ODQwMjExOC8zMTg3ODk2NjktYmYzMTdkNDAtNTY5Yy00ZGNmLWIxZGItOTZjZmQ3ZDhhYjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE1NTAzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiODE0ZjIxM2E1NzRkNjdmOTA1Y2FkMzM3Yjk2ZjE2MjI5MDdlNjU0OGU3OTkzZGFjNzZiNGU3NmIyMWU0ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.96sPsLxz-zfGhVrwZS-tVZ1WvL6JZ8yO7cP0_KL9KcQ"> 我对比了我们两个按钮差异的样式，css是有明显差异的，前缀为anzhiyu的丢失，可以检查一下是否存在自定义样式或者对主题的修改导致的问题，祝早日修复



虽然这么说很奇怪，我甚至无法确定是什么问题，但最终我找到了解决办法。

我尝试将域名从`www.jonastech.cc`换为`jonastech.cc`，结果页面的样式恢复了正常。随后，我又尝试了其他的域名（格式为`www.XXX.com`），它们也都是正常的。

只有在这个特定的域名`jonastech.cc`上，加上`www`别名后页面就变得不正常，这让我非常费解。现在我的方案是由www.重定向到顶级域名,反正能解决就行😮‍💨

**Comment by anzhiyu-c** [comment]
在hexo的配置文件中，配置一下域名
