### ISSUE TITLE
[Feature]: 优化建议

### ISSUE THREAD

**Issue by HimiCos** [anzhiyu-c/hexo-theme-anzhiyu#23]
### 想要的功能 | What feature do you want?

如果下面三个div内容文本过多，就会如图一，图二这样改怎样
我的逻辑是这样的：如果div中的文本换行，则会更改为图二的样式，如果未换行则不改变。
我暂时还没能力去修改这个 😂
![9db742f53d03bfe20c4839619a8f7d67](https://user-images.githubusercontent.com/92566148/232274659-845a78b4-4f35-4f71-8914-56268ae16726.png)
![59e808be2965eba6299f428ea39a714a](https://user-images.githubusercontent.com/92566148/232274661-d5dd1ba3-d713-41ae-b4b9-38ded577c962.png)

**Comment by anzhiyu-c** [comment]
已修复为超出自动换行
<img width="343" alt="image" src="https://user-images.githubusercontent.com/73864136/232280804-b008a511-8a60-4810-a1ad-e5c889e03d17.png">
<img width="330" alt="image" src="https://user-images.githubusercontent.com/73864136/232281187-bae0f3dd-710e-4d73-a358-abdc2c64b2c2.png">

**Comment by HimiCos** [comment]
nice!!!
