### ISSUE TITLE
[Bug]: 文档炸了！

### ISSUE THREAD

**Issue by itangqiao** [anzhiyu-c/hexo-theme-anzhiyu#233]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

undefined

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

<img width="1525" alt="image" src="https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/44393379/155ddf71-d0a9-4a97-94ca-db331aaf1f24">

### 出现问题的网站 | Website

https://docs.anheyu.com/

**Comment by anzhiyu-c** [comment]
已恢复
