### ISSUE TITLE
[Bug]: 随机文章失败

### ISSUE THREAD

**Issue by lirtual** [anzhiyu-c/hexo-theme-anzhiyu#235]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.12

### 使用的浏览器？ || What browse are you using?

Edge

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

macOS

### 问题描述 | Describe the bug

<img width="892" alt="image" src="https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/19893315/9e35ffac-9528-4564-aa04-fe229c822df1">

随机文章功能无反应刷新当前页面，使用浏览器调试发现随机文章的请求缺失了Host，我直接使用主题未添加额外修改且使用了模板默认的三篇文章的情况下，出现该问题。

### 出现问题的网站 | Website

localhost:4000

**Comment by anzhiyu-c** [comment]
无法复现该问题，需要更多信息。
