### ISSUE TITLE
[Feature]: 即刻与相册集图片建议

### ISSUE THREAD

**Issue by HimiCos** [anzhiyu-c/hexo-theme-anzhiyu#24]
### 问题：
即刻如果只是单张图片会这样
<img width="344" alt="45680da3a2b939bd53e327735567316a" src="https://user-images.githubusercontent.com/92566148/232300039-bf29b421-01cf-4973-bc72-57b36503fbcc.png">
如果是五张图会这样
<img src="https://user-images.githubusercontent.com/92566148/232300129-95f793ce-b38b-496b-a823-cc47146da6f1.png" alt="Image" width="300px">

相册集就是全部向下排列
### 建议：
一、可以试着修改只有一张图片的样式
二、使图片堆叠起来 加一个切换按钮
像这个[演示](https://orangleli.github.io/%E8%BD%AE%E6%92%AD%E5%9B%BE/%E6%99%AE%E9%80%9A%E8%BD%AE%E6%92%AD/%E6%99%AE%E9%80%9A%E8%BD%AE%E6%92%AD.html) 这里是：[源码](https://github.com/orangleLi/my-swiper)
三、使图片以不同大小的方式排列组合成一个长方形
类似于这样
<img src="https://user-images.githubusercontent.com/92566148/232301316-57cf7c96-2bbd-4e40-86d0-4d1366c5e3ef.jpg" alt="Image" width="300px">
总结：
相册集会比较推荐第三种方案 即刻比较推荐第一种
毕竟即刻图片不会太多

**Comment by hulebaji** [comment]
这个提议好哇

**Comment by anzhiyu-c** [comment]
下个版本支持。
