### ISSUE TITLE
[Bug]: 主页中部菜单错位

### ISSUE THREAD

**Issue by anyfrees** [anzhiyu-c/hexo-theme-anzhiyu#240]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

最新版

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

<img width="1238" alt="2024-06-29 171031" src="https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/131247791/80cc821c-6174-4dc5-8d34-e599552de810">

### 出现问题的网站 | Website

https://blog.anheyu.com/

**Comment by anzhiyu-c** [comment]
该问题出现在win平台上，确实是需要修复，但是介于目前的情况我没有win电脑，所以无法测试修复，还望体谅，如果可以，欢迎pr

**Comment by gyhmuuki** [comment]
> 该问题出现在win平台上，确实是需要修复，但是介于目前的情况我没有win电脑，所以无法测试修复，还望体谅，如果可以，欢迎pr
@anzhiyu-c 将\source\css\_extra\catalog_list\catalog_list.css中#catalog-list的overflow-x属性改为auto即可

**Comment by anzhiyu-c** [comment]
@anzhiyu-c anzhiyu-c  安之鱼C merged commit [e1b5371](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/commit/e1b5371299486f5bbd8bc1b4fc28572b2ccd1c7c)
