### ISSUE TITLE
[Bug]: 图片配置无效，不确定是bug还是哪里配置有问题

### ISSUE THREAD

**Issue by yixiu001** [anzhiyu-c/hexo-theme-anzhiyu#248]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.12

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

macOS

### 问题描述 | Describe the bug
配置好的图片一直不展示！！！
<img width="1369" alt="image" src="https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/48150701/3c84059b-515c-495a-aebc-a23701d7c62e">

### 出现问题的网站 | Website

还在本地部署

**Comment by anzhiyu-c** [comment]
信息太少，无法调试
1. 可能图片路径错了
2. 可能图片本来就无法访问
3. 可能原图有跨域
4. 可能图片不被允许本地访问

**Comment by yixiu001** [comment]
是特殊字符转义的问题我的title里面有英文引号
`title="一休's 博客"`
换成`title="一休‘s 博客"`就可以了
