### ISSUE TITLE
[Bug]: 访问统计移动端不显示

### ISSUE THREAD

**Issue by HimiCos** [anzhiyu-c/hexo-theme-anzhiyu#25]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.1.6

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

iOS

### 问题描述 | Describe the bug

安卓没测试

<img src="https://user-images.githubusercontent.com/92566148/232305472-e6dc10d6-f853-4d65-ae4d-4fdb3fcdfbac.jpeg" alt="Image" width="300px">

### 出现问题的网站 | Website

https://anzhiy.cn

**Comment by anzhiyu-c** [comment]
我这边移动端Chrome和safari都没问题

**Comment by HimiCos** [comment]
找到原因了
我开着梯子 连51LA的官网都进不去
关掉梯子就可以看到数据了😂

**Comment by scfcn** [comment]
我不开梯子也进不去
