### ISSUE TITLE
[Bug]: 网页缩小后，字体会重合

### ISSUE THREAD

**Issue by mlemontx** [anzhiyu-c/hexo-theme-anzhiyu#26]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.1.6

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

![微信截图_20230417164959](https://user-images.githubusercontent.com/125271764/232434982-5121ad13-5170-496e-b89f-c2c0f29f89b2.png)

### 出现问题的网站 | Website

https://yylemon.top/

**Comment by anzhiyu-c** [comment]
调整浏览器比例。

**Comment by mlemontx** [comment]
好的，鱼佬
