### ISSUE TITLE
[Bug]: LinkPageTop 显示不正常

### ISSUE THREAD

**Issue by CX330Blake** [anzhiyu-c/hexo-theme-anzhiyu#261]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

latest

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

友情链结已经超过30个，但是依然会有显示问题。
<img width="959" alt="image" src="https://github.com/user-attachments/assets/52197f48-daa6-49f3-9e80-9827e331c73c">

### 出现问题的网站 | Website

本地測試

**Comment by xyhcode** [comment]
你把右边卡片关掉试试

**Comment by anzhiyu-c** [comment]
暂时复现不了，能不能提供一个最小复现办法，我猜是友链少了点，直接复制到 50 个以上试试

**Comment by CX330Blake** [comment]
问题找到了，在pangu的配置中如果设为site有可能会出现layout问题，改为post即可。
