### ISSUE TITLE
[Bug]: AI摘要的Key直接明文展示，无论是什么AI，只要在任一帖子下按f12一查看就会泄露

### ISSUE THREAD

**Issue by Chal1ce** [anzhiyu-c/hexo-theme-anzhiyu#263]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.12

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

macOS

## 描述：
我直接以作者的网站为例，在帖子下，按f12，进入对应的html文件，找到GLOBAL_CONFIG全局配置，找到postHeadAiDescription，下面的key一览无余

## 图片：
![image](https://github.com/user-attachments/assets/6d3b221b-d8b7-4718-bcc0-beb85245cf8e)

### 出现问题的网站 | Website

https://blog.anheyu.com/posts/40fd.html

**Comment by chendada00** [comment]
这种纯静态的项目没办法啊，只能写死

**Comment by anzhiyu-c** [comment]
没事的，后端有校验，可以自己试试。

**Comment by mc-sep** [comment]
51LA的也一览无余

**Comment by Chal1ce** [comment]
没事，解决了，虽然后端有校验，不过可以自己起了个后端用别的模型和隐藏掉apikey @mc-sep
