### ISSUE TITLE
[Feature]: Twikoo评论更新

### ISSUE THREAD

**Issue by Echojjy** [anzhiyu-c/hexo-theme-anzhiyu#268]
### 想要的功能 | What feature do you want?

Twikoo评论系统现更新至1.6.39版本，前端版本低于云函数版本是否会造成一些问题？能否提供前端版本更新方法，或将主题Twikoo版本更新至于云函数相同版本？

**Comment by SwaggyMacro** [comment]
![image](https://github.com/user-attachments/assets/af7320d4-dc01-451c-80ac-b0c91b1dd052)

如果你要更新的话就配置自定义CDN

**Comment by acgurl** [comment]
我也遇到过这个问题了
由于我的twikoo设置了cloudflare的验证码，如果不自己配置cdn的话验证码无法加载，导致无法评论
能否将主题内置的前端文件更新一下？这已经有点影响使用了
![7e6e8b4221969740a03b3b2742302e75](https://github.com/user-attachments/assets/6170f32e-ecd2-4557-80ee-ee0e9732e320)

**Comment by liueic** [comment]
可以在 `theme/plugins.yml` 里面修改对应的版本，你要是感兴趣的话可以看我这一次的 commit：
https://github.com/liueic/hexo-theme-anzhiyu/commit/2954c1ec37297428bac2ed94a504c255edf54fb6
