### ISSUE TITLE
[Bug]: 文章内的部分图标消失

### ISSUE THREAD

**Issue by HimiCos** [anzhiyu-c/hexo-theme-anzhiyu#28]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.1.7

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

macOS

### 问题描述 | Describe the bug

我直接本地拉的最新的 包括hexo也是新建的
![CleanShot 2023-04-19 at 10 13 56@2x](https://user-images.githubusercontent.com/92566148/232948917-f67a3c4e-d1e7-4c53-86ec-99420ffd1312.png)
原本这里有一个小飞机
![CleanShot 2023-04-19 at 10 15 19@2x](https://user-images.githubusercontent.com/92566148/232949109-2126dfb3-621f-40db-84db-39709c207d0d.png)
这里最新的已经没有了
还有这里
![CleanShot 2023-04-19 at 10 16 41@2x](https://user-images.githubusercontent.com/92566148/232949242-ad9736f3-265d-4d98-820b-214911a27d59.png)

### 出现问题的网站 | Website

本地

**Comment by anzhiyu-c** [comment]
一直都有，我自己的博客就是最新版本。

**Comment by HimiCos** [comment]
是我的写法有问题吗 我在浏览器中能找到那个button元素 但是就是没见样式 奇怪
```
<div class="tabs" id="对比">
    <ul class="nav-tabs">
        <li class="tab active">
        <button type="button" data-href="#Hexo">Hexo</button>
        </li>
        <li class="tab">
        <button type="button" data-href="#Halo2">Halo2</button>
        </li>
    </ul>

<div class="tab-contents">
<div class="tab-item-content active" id="Hexo">

**优点：**

<button type="button" class="tab-to-top" aria-label="scroll to top"><i class="fas fa-arrow-up"></i></button>  
</div>

<div class="tab-item-content" id="Halo2">

**缺点：**

<button type="button" class="tab-to-top" aria-label="scroll to top"><i class="fas fa-arrow-up"></i></button>               
</div>
</div>
</div>
```
我再重新拉取一个最新的到本地试试看
