### ISSUE TITLE
[Bug]: 没有小剪刀

### ISSUE THREAD

**Issue by mlemontx** [anzhiyu-c/hexo-theme-anzhiyu#29]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.1.6

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

没有小剪刀，是主题少什么东西，还是网络问题呢？

![微信截图_20230419103620](https://user-images.githubusercontent.com/125271764/232952386-874d6a15-75a9-4457-bbdb-5ff7a03a584b.png)

### 出现问题的网站 | Website

http://localhost:4000/2023/04/16/Node/Node.js%20%E5%88%9D%E4%BD%93%E9%AA%8C/

**Comment by anzhiyu-c** [comment]
使用最新的main分支，或者更新图标为1.0.6版本。[更新图标版本为1.0.6](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/commit/194568c9b20269dfd80ed7e87e0f187d714b8ba6)
