### ISSUE TITLE
[Bug]: Mermaid无法正常渲染内容

### ISSUE THREAD

**Issue by ximuliunian** [anzhiyu-c/hexo-theme-anzhiyu#299]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.6.14

### 使用的浏览器？ || What browse are you using?

Edge

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

![image](https://github.com/user-attachments/assets/9a0d80fb-81a5-4fb9-9979-b621595eab4f)

我开启的配置文件的Mermaid开关，但是不能让其正常渲染

### 出现问题的网站 | Website

https://blog.ximuliunian.top/2024/11/03/java/GitHub%20OAuth/

**Comment by ximuliunian** [comment]
已经解决了，问题就是出现在一个class类名没有被锁定到，在mermaid.pug这个文件中。只需要把 `.mermaid-wrap` 中的 `-wrap` 去除就行了

**Comment by lustime** [comment]
这个在哪儿啊，我也遇到了同样的问题，另外 这个需要配置吗
if theme.mermaid.enable == true
  script(type='text/javascript', id='maid-script' mermaidoptioins=theme.mermaid.options src='https://unpkg.com/mermaid@'+ theme.mermaid.version + '/dist/mermaid.min.js' + '?v=' + theme.version)
  script.
    if (window.mermaid) {
      var options = JSON.parse(document.getElementById('maid-script').getAttribute('mermaidoptioins'));
      mermaid.initialize(options);
    }

**Comment by Grain021125** [comment]
提交了一个PR彻底解决了这个问题，并修复了手机端部分浏览器加载不渲染以及PJAX跳转不渲染的问题
