### ISSUE TITLE
[Bug]: 个人卡片显示问题

### ISSUE THREAD

**Issue by dazhuang17** [anzhiyu-c/hexo-theme-anzhiyu#3]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.0.2

### 使用的浏览器？ || What browse are you using?

Chrome

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

关于首页个人卡片
暗色模式下，on Studying 字体颜色为白色
![image](https://user-images.githubusercontent.com/84715052/229395471-f52c9116-c32a-41a2-b2c9-b17d39fbf702.png)

还有个...🐟佬，卡片的模式1，在浅色模式下，卡片背景好像是白色的...

### 出现问题的网站 | Website

本地搭建

**Comment by anzhiyu-c** [comment]
下个版本修复。

**Comment by dazhuang17** [comment]
个人卡片徽标上面的那个按钮，点击，跳转不到外部链接，比如说，B站
