### ISSUE TITLE
[Bug]: 关于页位置图溢出

### ISSUE THREAD

**Issue by fxm0402** [anzhiyu-c/hexo-theme-anzhiyu#31]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.1.8

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

![EJ}8%LNL(Q4H}D6J)C6MDHT](https://user-images.githubusercontent.com/70627786/233756552-7dfa43bf-10bd-4c52-beab-bec99d88a353.png)

### 出现问题的网站 | Website

blog.xiangming.site

**Comment by anzhiyu-c** [comment]
vscode格式化了配置文件导致的配置文件错误。
