### ISSUE TITLE
[Bug]:右键点击转为繁体后，再次点击应该切换为转为简体 

### ISSUE THREAD

**Issue by fxm0402** [anzhiyu-c/hexo-theme-anzhiyu#33]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.8

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

![image](https://user-images.githubusercontent.com/70627786/233884540-c1dbd32f-5eca-45ee-9508-a5b96487b505.png)
功能没有影响，就是有点不正常哈哈哈

### 出现问题的网站 | Website

blog.xiangming.site

**Comment by anzhiyu-c** [comment]
在繁体字下，所以显示为繁体。

**Comment by miaopasixx** [comment]
他说的有没有可能这几个字应该为繁体的'轉為簡體'。@anzhiyu
