### ISSUE TITLE
[Feature]: 可以自定义左上角标题为 icon 嘛

### ISSUE THREAD

**Issue by fxm0402** [anzhiyu-c/hexo-theme-anzhiyu#34]
### 想要的功能 | What feature do you want?

自己做了一个 icon ,想替换 左上角 title .搜索文件后，没有找到生成页面。求鱼佬看到后指导。或者出个自定义功能也好。哈哈哈（感觉有点过分）

**Comment by anzhiyu-c** [comment]
暂不支持替换左上角标题为icon，因为没有比较好的配置方式，可以自行引入icon后魔改，文件路径为`themes/anzhiyu/layout/includes/header/nav.pug`
