### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by SHINRAYDEV** [anzhiyu-c/hexo-theme-anzhiyu#35]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.1.8

### 使用的浏览器？ || What browse are you using?

Safari

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

macOS

### 问题描述 | Describe the bug

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/63151670/234745378-00372be7-4b39-4437-9b43-37740840f769.png">
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/63151670/234746298-f4efc087-7974-43c1-9132-b263d6c5ba82.png">
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/63151670/234746851-e993b398-b758-46ce-85d2-5ac84df28f3d.png">
Hello麻烦问下这里Safari浏览器下样式渲染是不是Bug

### 出现问题的网站 | Website

shinray.tech

**Comment by anzhiyu-c** [comment]
已修复 https://github.com/anzhiyu-c/hexo-theme-anzhiyu/commit/644e75031a04c322a317f6df607ed51e8286d27d
