### ISSUE TITLE
[Bug]: iPad网页适配有问题

### ISSUE THREAD

**Issue by milkman-wang** [anzhiyu-c/hexo-theme-anzhiyu#36]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

最新

### 使用的浏览器？ || What browse are you using?

Safari

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

iOS

### 问题描述 | Describe the bug

![](https://i.postimg.cc/q7xqq3Wh/8-B3-D0-F5-A-435-A-4-E7-B-A5-E8-F0-B1-F9-DB58-B3.png)

### 出现问题的网站 | Website

https://blog.milkman.top/

**Comment by milkman-wang** [comment]
导航栏部分

**Comment by milkman-wang** [comment]
自动切换深色模式也有问题，主题配置里已经改成1，但是不生效。Safari和edge都不生效。用原生butterfly是可以的

**Comment by anzhiyu-c** [comment]
导航栏关闭天气组件，顶部为文章太少。
