### ISSUE TITLE
[Bug]: aside.stly 中的 aside.card_author.type == 1 时 .card-widget的相关样式未正常显示的问题

### ISSUE THREAD

**Issue by xiaohuliqibao** [anzhiyu-c/hexo-theme-anzhiyu#37]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.1.8

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

在主题配置文件中 修改aside.card_author.type = 1 时，aside_card 的整体渲染为#fff 白色，通过修改 aside.stly 调整 background的值发现也没有用。最后发现问题可能出在 第511行 没有添加 .card-widget

### 出现问题的网站 | Website

暂时没有

**Comment by anzhiyu-c** [comment]
将`aside.card_author.description`修改为以下内容或自定义内容：
```html
<div style="line-height:1.38;margin:0.6rem 0;text-align:justify;color:rgba(0, 0, 0, 0.8);">这有关于<b >产品、设计、开发</b>相关的问题和看法，还有<b >文章翻译</b>和<b >分享</b>。</div><div style="line-height:1.38;margin:0.6rem 0;text-align:justify;color:rgba(0, 0, 0, 0.8);">相信你可以在这里找到对你有用的<b >知识</b>和<b >教程</b>。</div>
```
