### ISSUE TITLE
[Bug]: essay页面推荐歌曲的歌词显示被遮挡

### ISSUE THREAD

**Issue by Fly1216** [anzhiyu-c/hexo-theme-anzhiyu#38]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.1.8

### 使用的浏览器？ || What browse are you using?

Edge

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

![EJ9~REM %3ARR_W69W4QN`I](https://user-images.githubusercontent.com/85989926/235044021-8438d361-b4ed-4f65-a0de-a5c5ac3658c5.jpg)

![J`OT}F`$_$XZ2O5` CE5CY2](https://user-images.githubusercontent.com/85989926/235044039-39e30e84-8596-4149-a92b-7f36b1857bd7.jpg)

浅色模式下，歌词被遮挡一点点
深色模式下，歌词被遮挡一半

### 出现问题的网站 | Website

http://flyohh.cn/

**Comment by anzhiyu-c** [comment]
已修复 https://github.com/anzhiyu-c/hexo-theme-anzhiyu/commit/23f0fa06798e1769066287b0758063b95136741d
