### ISSUE TITLE
[Bug]: 关于页面的赞赏名单中，最新更新时间只显示捐赠最多的人的时间，而不是最新时间.

### ISSUE THREAD

**Issue by momo54181** [anzhiyu-c/hexo-theme-anzhiyu#39]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.1.8

### 使用的浏览器？ || What browse are you using?

Edge

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

![image](https://user-images.githubusercontent.com/79344479/235445104-ddc475f4-4831-4173-b324-185465fa4431.png)

### 出现问题的网站 | Website

https://blog.mocn.top/about/

**Comment by anzhiyu-c** [comment]
排序规则为，优先金额排序，然后时间排序。
