### ISSUE TITLE
[Bug]: 手机端文章页不显示图片

### ISSUE THREAD

**Issue by momo54181** [anzhiyu-c/hexo-theme-anzhiyu#40]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.1.8

### 使用的浏览器？ || What browse are you using?

Other

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

Android

### 问题描述 | Describe the bug

使用FireFox浏览器

![f403a9c6fe461763904088ac8c2d68e](https://user-images.githubusercontent.com/79344479/235453382-7f3d181d-4a2e-40d0-8968-3e62fd435655.jpg)

### 出现问题的网站 | Website

https://blog.mocn.top/posts/455dc8a1/

**Comment by anzhiyu-c** [comment]
图床问题不会修复。

**Comment by momo54181** [comment]
好吧
