### ISSUE TITLE
[Bug]: hexo g 报错--1.1.9

### ISSUE THREAD

**Issue by fu-jw** [anzhiyu-c/hexo-theme-anzhiyu#43]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.1.9

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

使用1.1.8 的时候没问题

如图:

![Snipaste_2023-05-09_19-16-27](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/40262591/f965b2d0-5208-4d87-ac30-86009cae7af5)

### 出现问题的网站 | Website

本地

**Comment by anzhiyu-c** [comment]
该问题在1.1.10版本中得到解决，或者参照文档配置`_config.anzhiyu.yml`可以解决。

**Comment by fu-jw** [comment]
升级后确实没问题了,但1.1.10版的日志打印信息还显示: 1.1.9
不影响使用

**Comment by anzhiyu-c** [comment]
> 升级后确实没问题了,但1.1.10版的日志打印信息还显示: 1.1.9 不影响使用

没升级完全
