### ISSUE TITLE
[Bug]: 音乐馆页面黑屏

### ISSUE THREAD

**Issue by kevinwu06** [anzhiyu-c/hexo-theme-anzhiyu#49]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.2.0

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

音乐馆按照主题配置文档配置后，显示黑屏，只有右下角的播放控制按键
![微信截图_20230522214219](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/120035670/7b0b8f63-f6a7-412a-be83-8175812317f6)

### 出现问题的网站 | Website

https://www.kevinwu.cc/box/music/

**Comment by anzhiyu-c** [comment]
meting未加载，请检查配置

**Comment by kevinwu06** [comment]
好的现在可以了，感谢鱼佬
