### ISSUE TITLE
[Bug]: 相册地址图标丢失

### ISSUE THREAD

**Issue by xyhcode** [anzhiyu-c/hexo-theme-anzhiyu#5]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.0.7

### 使用的浏览器？ || What browse are you using?

Chrome

### 使用的系统？ || What operating system are you using?

macOS

### 问题描述 | Describe the bug

<img width="492" alt="image" src="https://user-images.githubusercontent.com/64968400/229565558-5fbe715f-0f54-4c7e-b5e9-05ef529b520d.png">

### 出现问题的网站 | Website

本地

**Comment by anzhiyu-c** [comment]
下个版本修复。
