### ISSUE TITLE
[Bug]: about 页面文字显示问题

### ISSUE THREAD

**Issue by HoarfrostRaven** [anzhiyu-c/hexo-theme-anzhiyu#50]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

dev

### 使用的浏览器？ || What browse are you using?

Safari

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

macOS

### 问题描述 | Describe the bug

about 页面追求那一栏文字显示有问题，当单词过长时无法显示全，并且有空格的时候只会显示后面的单词

### 出现问题的网站 | Website

https://hoarfrostraven.github.io/about/

**Comment by anzhiyu-c** [comment]
看起来是您自行修改了部分css造成的问题，默认主题是没有问题的

**Comment by HoarfrostRaven** [comment]
我确定我只按照文档修改过主题配置文件的内容，没有修改过css部分的内容
