### ISSUE TITLE
[Feature]: 大神我想请问下 meting-api今天突然跨域了用不了了，我部署好了自己api服务但是不知道该在哪里配置呢 或者有什么其他的办法

### ISSUE THREAD

**Issue by Yc100** [anzhiyu-c/hexo-theme-anzhiyu#52]

**Comment by geekswg** [comment]
> 配置文件 `_config.anzhiyu.yml` 修改 `meting_api`为你自己的api

**Comment by Mitpoppy** [comment]
> > 配置文件 `_config.anzhiyu.yml` 修改 `meting_api`为你自己的api

请问有自建meting api的教程吗或者文档

**Comment by lz732895965** [comment]
我也是遇到这个问题，我试着按照上面的方案修改配置文件` _config.anzhiyu.yml `修改` meting_api`为你自己的api，但是在控制台中仍然提示有错误，不知道怎么解决。

**Comment by geekswg** [comment]
这里有教程
[这里有教程](https://hexo.geekswg.top/posts/3a28.html)

**Comment by anzhiyu-c** [comment]
参考文章[自建meting API](https://blog.anheyu.com/posts/a76e.html)
