### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by xy055878** [anzhiyu-c/hexo-theme-anzhiyu#54]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.3.1

### 使用的浏览器？ || What browse are you using?

Edge

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

![N6XY %H8H%ESITMZAI4J% X](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/103242495/fe281230-b281-4530-abbd-4b631a0383de)

页脚链接复制按钮失效

### 出现问题的网站 | Website

tany.top

**Comment by xyhcode** [comment]
确实，我也有一样的问题

**Comment by anzhiyu-c** [comment]
将在下个版本得到修复。
