### ISSUE TITLE
[Feature]: 即刻说说支持视频播放

### ISSUE THREAD

**Issue by lz732895965** [anzhiyu-c/hexo-theme-anzhiyu#57]
### 想要的功能 | What feature do you want?

未来有没有可能在即刻说说页面支持视频播放。例如支持多吉云视频或者其他来源的视频

**Comment by anzhiyu-c** [comment]
在即刻添加视频会卡住整个页面的加载，所以不推荐在即刻页面添加视频的操作，不过未来依然可能会进行支持，是否使用取决于用户的想法💡了。
