### ISSUE TITLE
[Bug]: 主题显示问题

### ISSUE THREAD

**Issue by Alcexn** [anzhiyu-c/hexo-theme-anzhiyu#58]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.3.1

### 使用的浏览器？ || What browse are you using?

Edge

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

Linux

### 问题描述 | Describe the bug

手机端显示问题，在首页文章区，时间，更新时间等显示太挤了，在官网没有这个问题，还有在文章页面中，二维码显示有问题，还有文章对不齐有缝
![Screenshot_20230622_162757_com microsoft emmx](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/125755021/4d8589e4-c133-4a88-a9c5-ee9aff4e6acd)
![Screenshot_20230622_162751_com microsoft emmx](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/125755021/520228be-6ddc-4eb7-9831-a1a5adc57211)

### 出现问题的网站 | Website

https://hblog-dusky.vercel.app/

**Comment by gtwxxh666** [comment]
第2个好像已经修复了

**Comment by anzhiyu-c** [comment]
第一个问题是由于移动端兼容问题，目前测试ios端夸克，safair，谷歌，edge等浏览器没有问题，由于我没有安卓设备，所以无法定位具体问题，猜测是因为QR code在浏览器端传递参数创建固定大小二维码兼容性有问题，暂时没有很好的解决办法。

**Comment by gtwxxh666** [comment]
鱼佬，通过我的荣耀安卓机测试，的确有显示的问题（二维码，首页日期，右侧有缝，使用的是Edge浏览器
![Screenshot_20230701_122201_com microsoft emmx](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/98093034/c43d4b2c-f784-418b-837d-03d226859cbf)
![Screenshot_20230701_122326_com microsoft emmx](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/98093034/5758182e-268e-43f9-a0f0-8bc887a36dbd)
![Screenshot_20230701_122343_com microsoft emmx](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/98093034/1bf09743-5884-4ba4-ba3e-eb43580b70df)
