### ISSUE TITLE
[Bug]: 右下角鱼图标打开的控制台对不齐，标签显示不全问题

### ISSUE THREAD

**Issue by backunderstar** [anzhiyu-c/hexo-theme-anzhiyu#6]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.08

### 使用的浏览器？ || What browse are you using?

Edge

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

![联想截图_20230404203815](https://user-images.githubusercontent.com/89375248/229818955-618e957d-62ab-4a03-8806-2aa9c5aeadd7.png)
如图，如标题。
当文章发表月份少于5月，上面格子对不齐，标签显示不全。

### 出现问题的网站 | Website

www.backunderstar.com

**Comment by anzhiyu-c** [comment]
暂时解决办法将文章发表月份增多，该问题将在下个版本得到改进。
