### ISSUE TITLE
[Bug]: 关于页面的skillsTips不显示

### ISSUE THREAD

**Issue by haloged** [anzhiyu-c/hexo-theme-anzhiyu#60]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.3.1

### 使用的浏览器？ || What browse are you using?

Edge

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

控制台里没有任何关于这个的请求失败等，首页的也显示不出来。
![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/101408211/9d3fb3de-16c7-4e2f-b592-a3c2a2e59090)

### 出现问题的网站 | Website

https://test.haloged.eu.org/about/

**Comment by anzhiyu-c** [comment]
配置`creativity.yml`，关于的内容是读取此yml
