### ISSUE TITLE
[Bug]: 控制台icon颜色异常

### ISSUE THREAD

**Issue by Ganzhe2028** [anzhiyu-c/hexo-theme-anzhiyu#66]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.4.0-dev 我是7月7日更新的

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

开启首页顶图后，手机端light模式下控制台icon颜色异常：
![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/129269449/598f3074-1fb9-4e81-a3ea-1573f6100268)

### 出现问题的网站 | Website

https://ganzhe2028.github.io/

**Comment by anzhiyu-c** [comment]
1.4.1版本已修复当前问题。
