### ISSUE TITLE
[Bug]: issues中的问题

### ISSUE THREAD

**Issue by ning0818** [anzhiyu-c/hexo-theme-anzhiyu#67]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

None

### 使用的浏览器？ || What browse are you using?

None

### 是否修改过主题文件？ || Has the theme files been modified?

None

### 使用的系统？ || What operating system are you using?

None

### 问题描述 | Describe the bug

issues中说
> Questions about Butterfly
>一些使用问题请到 Discussion 询问。 Please ask questions in Discussion.
但是 Discussion 并没有开启
![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/117955401/4f89d309-4a9e-4cf3-ad94-d1deb03ba5ac)

### 出现问题的网站 | Website

https://github.com/anzhiyu-c/hexo-theme-anzhiyu/issues/new/choose

**Comment by anzhiyu-c** [comment]
已开启，更多的建议在QQ群聊中询问，热心的群友会给出你想要的答案。
