### ISSUE TITLE
[Questions]: 如何页脚定义文字

### ISSUE THREAD

**Issue by ning0818** [anzhiyu-c/hexo-theme-anzhiyu#68]
### 想要的功能 | What feature do you want?

![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/117955401/989dd3eb-91ab-43e0-8990-5ee4c0122516)
主题文档中并没有说明如何设置“页脚你好自动定义文字”

**Comment by geekswg** [comment]
custom_text

**Comment by anzhiyu-c** [comment]
配置文件搜索`custom_text `
