### ISSUE TITLE
[Feature]: 希望支持waline的表情包功能和自定义图床功能

### ISSUE THREAD

**Issue by ning0818** [anzhiyu-c/hexo-theme-anzhiyu#78]
### 想要的功能 | What feature do you want?

希望支持waline的表情包功能和自定义图床功能
正如官方文档所说
### 表情：
https://waline.js.org/guide/features/emoji.html#例子
```
···
    // 设置 emoji 为微博与哔哩哔哩
    emoji: [
      '//unpkg.com/@waline/emojis@1.1.0/weibo',
      '//unpkg.com/@waline/emojis@1.1.0/bilibili',
    ],
···
```
### 图床：
https://waline.js.org/cookbook/customize/upload-image.html#案例

**Comment by CCKNBC** [comment]
@ning0818 dev 版本目前已支持
@anzhiyu-c 可以关闭此 issue
