### ISSUE TITLE
[Bug]: 文章版权丢失样式，两个头像

### ISSUE THREAD

**Issue by gongjuecloak** [anzhiyu-c/hexo-theme-anzhiyu#81]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.5.1

### 使用的浏览器？ || What browse are you using?

Edge

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/100070999/bd3919c1-a54b-4293-9510-24a990349fcc)

### 出现问题的网站 | Website

http://blog.gjcloak.top/

**Comment by anzhiyu-c** [comment]
在我这边看到是一个头像。
