### ISSUE TITLE
[Bug]: 配置文件中关闭pjax后无法进入相册集详情页

### ISSUE THREAD

**Issue by linanyang** [anzhiyu-c/hexo-theme-anzhiyu#82]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.5.1

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

配置文件中关闭pjax后无法进入相册集详情页；
Page Front-matter中设置了top_img，但是无法显示 [https://yanhua.cc/nav/](url)

### 出现问题的网站 | Website

https://yanhua.cc/album/

**Comment by anzhiyu-c** [comment]
Pjax是主题的重要基础功能，关闭会导致大量功能无法使用
top_img仅文章支持设置，顶部的图片我这边看你已经设置好了。
