### ISSUE TITLE
[Bug]: Menu 子选项无法保持显示

### ISSUE THREAD

**Issue by Xyyaua** [anzhiyu-c/hexo-theme-anzhiyu#88]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.5.3

### 使用的浏览器？ || What browse are you using?

Other

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

如题，鼠标离开menu按钮后

在PC设备上的，移动端不受影响
不过这个bug比较随缘，有时候可以正常使用（其他设备没有测试

暂时解决方案：
打开开发者工具

https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/44024543/ab7f5844-30ef-4b11-afdb-e614944045d5

### 出现问题的网站 | Website

任何使用这个主题的网站

**Comment by anzhiyu-c** [comment]
虽然这并不是主题的bug，因为你不是正常使用nav的保持，而是在反复挑逗，但是下个版本这个问题将得到一定程度的优化。

**Comment by Xyyaua** [comment]
_已更新到1.6.12_
bug与浏览器扩展有关
在装有[浮图秀](https://github.com/Mr-VincentW/PhotoShow)扩展并启用时，就会导致这个问题发生
_现在也有_
