### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ayakasuki** [anzhiyu-c/hexo-theme-anzhiyu#89]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.5.3

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

是 (Yes)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

理论上image支持video播放，视频能正常播放，但是不能显示缩略图？
![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/20859971/30000d8e-a244-4ea9-8f54-27021b2be5af)

### 出现问题的网站 | Website

https://ayakasuki.com/essay/

**Comment by anzhiyu-c** [comment]
`<img>`标签是用于显示图像的 HTML 元素，而不是用于加载视频文件的。如果您想加载和播放 MP4 视频文件，应该使用 `<video>` 标签。

即刻暂时不支持视频展示，因为会拖慢加载速度，不过将在下个版本加入即刻视频。
