### ISSUE TITLE
[Bug]: anzhiyu-theme-static 似乎版本管理失效，同版本静态资源不一致

### ISSUE THREAD

**Issue by insilen** [anzhiyu-c/hexo-theme-anzhiyu#90]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.5.3

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

macOS

### 问题描述 | Describe the bug

尝试使用COS+CDN 建立该主题所有静态资源自托管资源，创建方法为建立一个子目录 使用命令

```shell
npm install anzhiyu-theme-static anzhiyu-blog-static instant.page pace-js pjax @fancyapps/ui node-snackbar vanilla-lazyload  hexo-anzhiyu-music butterfly-extsrc
```

然后使用同步脚本 把node_modules目录同步到腾讯COS对象存储中并定期更新，以上步骤经测试验证基本没有太大问题。唯独发现自托管字体资源缺失，而博主的该资源位于

`https://cdn.cbd.int/anzhiyu-theme-static@1.1.9/icon/font_2508400_fpn9ui60u6q.woff2`

版本为1.1.9 
经排查在 npmjs.com中查询

`https://www.npmjs.com/package/anzhiyu-theme-static/v/1.1.9?activeTab=code` 

版本为1.1.9 中没有对应字体资源，版本管理似乎不一致

期待博主统一出一个所有静态资源自托管仓库呗，主题非常给力 已为博主发电 不成敬意

### 出现问题的网站 | Website

http://localhost:4000

**Comment by anzhiyu-c** [comment]
<img width="1679" alt="image" src="https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/73864136/315c81c8-b57f-4fc4-a11c-c3b5e0bb9f64">
实际上有的，我截图在这里了（网络不好可能加载不出来）

**Comment by insilen** [comment]
感谢提醒，发现了是魔法问题 切换🪜后重新 npm update之后 anzhiyu-theme-static 中的字体出来了
