### ISSUE TITLE
[Bug]: 首页即刻banner样式出现了溢出

### ISSUE THREAD

**Issue by junpengzhou** [anzhiyu-c/hexo-theme-anzhiyu#92]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.5.3

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/22519817/e3feafe8-5f5a-484b-a723-84bad02cf29b)
出现图中情况，会溢出
配置方式按照主题文档的进行的
![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/22519817/f239be2c-f62b-40b1-8b85-21427628dec9)

### 出现问题的网站 | Website

本地复现

**Comment by junpengzhou** [comment]
定位出原因，因为升级了swiper导致，看看是否能适配新的swiper.bundle.js(#version:10.1.0) #58

**Comment by anzhiyu-c** [comment]
swiper存在很多版本，主题不会去适配所有版本，而是选择锁版本，默认的配置文件是能够加载的，该问题不会被修复。
