### ISSUE TITLE
[Bug]: 出现异常通知popup-windows样式，通知 你好呀

### ISSUE THREAD

**Issue by junpengzhou** [anzhiyu-c/hexo-theme-anzhiyu#94]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.5.4

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

Windows

### 问题描述 | Describe the bug

![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/22519817/518498ed-a98d-4cb3-a7b9-5b3fab574d8b)
有出现：通知，你好呀的字样出来，移动端也有发现，目前看是偶现，还没细看代码和调试情况如下
![image](https://github.com/anzhiyu-c/hexo-theme-anzhiyu/assets/22519817/c6bca02e-8fef-438e-85ae-26ef4748b46d)

### 出现问题的网站 | Website

https://blog.anheyu.com/posts/61e4.html

**Comment by anzhiyu-c** [comment]
清除缓存也存在这种情况吗？一个会话窗口只会在第一次打开首页的时候产生这个弹窗。

**Comment by junpengzhou** [comment]
清理过缓存

**Comment by anzhiyu-c** [comment]
无痕模式有这种情况吗

**Comment by i-FangTang** [comment]
cdn 浏览器 都要清除 才会正常

**Comment by anzhiyu-c** [comment]
> cdn 浏览器 都要清除 才会正常

我觉得是swpp遗留症

**Comment by junpengzhou** [comment]
没再出现，可关闭
