### ISSUE TITLE
主页开源吗？

### ISSUE THREAD

**Issue by AndersonHJB** [anzhiyu-c/hexo-theme-anzhiyu#95]
### 使用的 AnZhiYu 版本？ | What version of AnZhiYu are you use?

1.5.4

### 使用的浏览器？ || What browse are you using?

Chrome

### 是否修改过主题文件？ || Has the theme files been modified?

不是 (No)

### 使用的系统？ || What operating system are you using?

macOS

### 问题描述 | Describe the bug

https://index.anheyu.com/ 这个开源吗？

### 出现问题的网站 | Website

none

**Comment by anzhiyu-c** [comment]
暂无计划。
